[platformio]

default_envs = nano328p

[common]
pport = COM7    ; port fpr 328p
pbport = COM6   ; port for 328pb

[env]
platform = atmelavr
framework = arduino

monitor_speed = 230400

upload_protocol = urclock
board_build.core = minicore
board_build.f_cpu = 16000000L   ; 16 MHz Quarz (for 8 MHz change to 8000000L)

lib_deps =
    greiman/SdFat @ ^2.2.3

; ====================================================================
; 1. Arduino Nano with ATmega328PB (MiniCore)
; ====================================================================
[env:nano328pb]
board = ATmega328PB

upload_port = ${common.pbport}
monitor_port = ${common.pbport}
upload_speed = 115200

; ====================================================================
; 2. Standard Arduino Nano with ATmega328P
; ====================================================================
[env:nano328p]
board = ATmega328P

upload_port = ${common.pport}
monitor_port = ${common.pport}
;upload_speed = 57600            ; some Nano boards have problems with one or the other setting, check it out
upload_speed = 115200

board_build.variant = standard    ; <- Standard Pinout for 328P
