[platformio]
; Hier wählst du aus, welche Umgebung standardmäßig kompiliert werden soll:
default_envs = nano328p

; Gemeinsame Einstellungen für alle Umgebungen (vermeidet doppeltem Code)
[common]
pport = COM7    ; port fpr 328p
pbport = COM6   ; port for 328pb

[env]
platform = atmelavr
framework = arduino

monitor_speed = 230400

upload_protocol = urclock
board_build.core = minicore
board_build.f_cpu = 16000000L   ; 16 MHz Quarz (bei 8 MHz auf 8000000L ändern)

; Bibliotheken für beide Umgebungen
lib_deps =
    greiman/SdFat @ ^2.2.3

; ====================================================================
; 1. Arduino Nano mit ATmega328PB (unter Verwendung von MiniCore)
; ====================================================================
[env:nano328pb]
board = ATmega328PB

upload_port = ${common.pbport}
monitor_port = ${common.pbport}
upload_speed = 115200

; ====================================================================
; 2. Standard Arduino Nano mit ATmega328P
; ====================================================================
[env:nano328p]
; Nutze 'nanoatmega328new' für neue Bootloader (115200 Baud) 
; oder 'nanoatmega328' für alte Bootloader (57600 Baud)
;board = nanoatmega328new
board = ATmega328P

upload_port = ${common.pport}
monitor_port = ${common.pport}
;upload_speed = 57600            ; manchmal geht 57600 nicht und 115200 ist zu verwenden oder umgekehrt -> China Nano Clones
upload_speed = 115200

board_build.variant = standard    ; <- Standard Pinout für 328P
